### ISSUE TITLE
Release .NetStandard NuGet package

### ISSUE THREAD

**Issue by YakhontovYaroslav** [justcoding121/Advanced-Algorithms#2]
Any plans for targeting .NetStandard 1/2 and releasing all this great work as a NuGet package?

**Comment by justcoding121** [comment]
Hello. I am not planing to do a package in near future, since my intent was not to create an algorithm library. There is large number of optimizations possible in existing implementations here before to be considered for a library package. 

You can copy the code in each algorithm independently if needed since most are independent of other algorithms. PRs are welcome.

**Comment by justcoding121** [comment]
Just made a release

https://www.nuget.org/packages/Advanced.Algorithms

**Comment by YakhontovYaroslav** [comment]
@justcoding121 Thanks for your attention and sharing this on nuget.

I'll definitely consider firing PRs (at least on my 2nd issue), but unfortunately i'm too busy now with all the stuff at work + contributing to ASP.NET repo.
